#!/usr/bin/python

import sys
import os
import webbrowser
import musicbrainz2.disc
import musicbrainz2.webservice

if __name__ == '__main__':
    disc = musicbrainz2.disc.readDisc()
    query = musicbrainz2.webservice.Query()

    try:
        filter = musicbrainz2.webservice.ReleaseFilter(discId=disc.getId())
        results = query.getReleases(filter)
    except musicbrainz2.webservice.WebServiceError, e:
        print "Error:", e
        sys.exit(1)

    if len(results) == 0:
        url = musicbrainz2.disc.getSubmissionUrl(disc)
        if url:
            webbrowser.open_new(url)
        else:
            print >>sys.stderr, 'musicbrainz: no url received from server'
            sys.exit(1)
    else:
        print >>sys.stderr, 'musicbrainz: discid is already entered'
        sys.exit(2)
