#!/bin/sh

# for alsa, 'aplay -q -t raw -c 2 -r 44100 -f S16_LE'
DEFAULT_PLAY='play -q -t raw -c 2 -r 44100 -s -L -2 -'

if [ ! -t 0 ]; then
    echo "peel is now a wrapper script, and will set up a peel-encode"
    echo "pipeline for you. Run it without sending any data to stdin."
    exit 2
fi

until mbget -s; do
    echo "Could not find disc. Trying to submit to MusicBrainz..."
    mbsubmit
    echo -n "Did that work? (Yes/no) "; read ans
    case "$ans" in
        n|no) exit 1;;
    esac
done

echo -n "Is this data OK? (Yes/edit/quit) "; read ans
case "$ans" in
    e|edit) need_edit=1;;
    q|quit) exit 0;;
esac

tmp="$(mktemp -t peel.XXXXXXXXXX)"
mbget >"$tmp"
test "$need_edit" && ${EDITOR:-vi} "$tmp"

peel-encode "$@" <"$tmp" | peel-buffer "${PEEL_PLAY:-$DEFAULT_PLAY}"
rm -f "$tmp"
