#!/bin/sh

if command -v aplay >/dev/null 2>&1; then
    DEFAULT_PLAY='aplay -q -t raw -c 2 -r 44100 -f S16_LE'
else
    DEFAULT_PLAY='play -q -t raw -c 2 -r 44100 -s -L -2 -'
fi

if [ ! -t 0 ]; then
    printf 'peel is now a wrapper script, and will set up a peel-encode\n'
    printf 'pipeline for you. Run it without sending any data to stdin.\n'
    exit 2
fi

until mbget -s; do
    printf 'Could not find disc. Trying to submit to MusicBrainz...\n'
    mbsubmit
    printf 'Did that work? ([Y]es/[n]o) '; read ans
    case "$ans" in
        n|no) exit 1;;
    esac
done

printf 'Is this data OK? ([Y]es/[e]dit/[q]uit) '; read ans
case "$ans" in
    e|edit) need_edit=1;;
    q|quit) exit 0;;
esac

tmp="$(mktemp -t peel.XXXXXXXXXX)"
mbget >"$tmp"
test "$need_edit" && ${EDITOR:-vi} "$tmp"

peel-encode "$@" <"$tmp" | peel-buffer | ${PEEL_PLAY:-$DEFAULT_PLAY}
rm -f "$tmp"
