#!/bin/sh

until mbget -s; do
    echo "Could not find disc. Trying to submit to MusicBrainz..."
    mbsubmit
done

tmp=$(mktemp -t peel.XXXXXXXXXX)
mbget >"$tmp"

echo -n "Is this data OK? (yes/edit/quit) "
read ans

case "$ans" in
    e) ${EDITOR:-vi} "$tmp";;
    q) exit 0;;
esac

peel <"$tmp" | ${UNPEEL_PLAY:-funnel aplay -q -t raw -c 2 -r 44100 -f S16_LE}
rm -f "$tmp"
